### PR TITLE
Update __init__.py

### LINKED ISSUE #6: KeyError: 'name'
## Version of the custom_component

VERSION = "0.2.1"

## Configuration

```yaml
readme:
```

## Describe the bug
Key error with hacs.repositories file.

## Debug log

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/readme/__init__.py", line 168, in service_generate
    hacs_components = get_hacs_components(hass)
  File "/config/custom_components/readme/__init__.py", line 208, in get_hacs_components
    "name": get_repository_name(repository),
  File "/config/custom_components/readme/__init__.py", line 221, in get_repository_name
    name = repository["repository_manifest"]["name"]
KeyError: 'name'
```

### PR DESCRIPTION
**Pull request by aneisch**
Fix #6

### CODE REVIEW

**Comment by aneisch** [comment]
May not be the best way to fix, but addresses `hacs.repositories` entries with missing `name` key. e.g:
```json
        "127251446": {
            "authors": [
                "@xirixiz"
            ],
            "category": "integration",
            "description": "Provides sensors for the Dutch waste collector mijnafvalwijzer.nl and/or afvalstoffendienstkalender.nl",
            "domain": null,
            "downloads": 0,
            "first_install": true,
            "full_name": "xirixiz/Home-Assistant-Sensor-Afvalwijzer",
            "installed": false,
            "installed_commit": null,
            "last_commit": "eeae56c",
            "last_release_tag": "4.3.1",
            "last_updated": "2020-06-17T08:09:01Z",
            "name": null,
            "new": false,
            "repository_manifest": {},
            "selected_tag": null,
            "show_beta": false,
            "stars": 37,
            "topics": [],
            "version_installed": null
        },
```

**Comment by ludeeus** [comment]
This will not fix anything, when you get a KeyError, the key ("name") does not exist in the dictionary, HACS always writes that key no matter if it has a value or not so key will still be there with a value of `null` (None) :man_shrugging:

**Comment by aneisch** [comment]
I reverted the changes and now receive this again:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 656, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/readme/__init__.py", line 168, in service_generate
    hacs_components = get_hacs_components(hass)
  File "/config/custom_components/readme/__init__.py", line 208, in get_hacs_components
    "name": get_repository_name(repository),
  File "/config/custom_components/readme/__init__.py", line 221, in get_repository_name
    name = repository["repository_manifest"]["name"]
KeyError: 'name'
```

Perhaps there is something else I can look into?

**Comment by steve-gombos** [comment]
Are you able to find the exact repository that this is blowing up on?  Or include your .storage/hacs folder?  

I went through the HACS components I have installed and several of them have no name element in the repository_manifest, but I am not seeing the error which you are seeing.

**Comment by ludeeus** [comment]
OH!!!!, it uses the integration_manifest, and not the full dataset

This implementation should probably be redone to just use HACS, instead of reading files.

For the change, it should be:

```python
repository["repository_manifest"].get("name", repository["full_name"].split("/")[-1])
```

**Comment by steve-gombos** [comment]
True. Files way the quick and dirty way I came up with. I'll explore the HACS approach this weekend.

**Comment by ludeeus** [comment]
@steve-gombos Don't attempt a rewrite before this is merged https://github.com/hacs/integration/pull/1367 since that changes the structure of HACS quite a bit.

**Comment by steve-gombos** [comment]
Thanks for the heads up.

**Comment by ludeeus** [comment]
Closing this as #8 fixed #6

**Pull request closed without merging**
